[versions]
agp = "8.11.1"
foundation = "1.8.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
material3 = "1.3.2"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.2"
navigationComposeJvmstubs = "2.9.2"
navigationComposeVersion = "2.7.7"
appcompat = "1.7.1"
firebaseCrashlyticsBuildtools = "3.0.6"
#ksp = "1.9.22-1.0.17"
composeCompiler = "1.6.10"
firebaseAi = "17.8.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-compose-v277 = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose-jvmstubs = { group = "androidx.navigation", name = "navigation-compose-jvmstubs", version.ref = "navigationComposeJvmstubs" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
firebase-ai = { group = "com.google.firebase", name = "firebase-ai", version.ref = "firebaseAi" }

# ДОБАВЬТЕ эти библиотеки
#androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version = "2.6.1" }
#androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.6.1" }
#google-generative-ai = { group = "com.google.ai.client.generativeai", name = "generativeai", version = "0.7.0" }
#coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.6.0" }
#gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
#accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.34.0" }
#accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version = "0.34.0" }
#camerax-core = { group = "androidx.camera", name = "camera-core", version = "1.3.4" }
#camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version = "1.3.4" }
#camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version = "1.3.4" }
#camerax-view = { group = "androidx.camera", name = "camera-view", version = "1.3.4" }
#datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.1" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }